model_name: /home/user5/text/.models/mm-bert-4

data:
  valid_parquet_path: /home/user5/text/valid1.parquet
  parquet_path: /home/user5/text/clustres_output/updated_dataset.parquet
  val_ratio: 0.1
  num_workers: 2
  upsample: false
  downsample: false

training:
  batch_size: 8
  num_epochs: 10
  gradient_accumulation_steps: 64
  max_seq_length: 2048
  mixed_precision: true
  attention_implementation: flash_attention_2
  #gradient_clip_val: 1.0
  seed: 42
  resume_from: null
  supcon_temperature: 0.07
  classification_loss_weight: 0.5
  metric_loss_weight: 2.0

optimizer:
  learning_rate: 3.0e-5
  weight_decay: 0.01

scheduler:
  warmup_steps: 100
  num_training_steps: null
  name: cosine 
  num_cycles: 0.5

checkpointing:
  checkpoints_dir: /home/user5/text/checkpoints_3
  save_every_n_bathces: 500
  save_best_by: f1  # options: loss, acc, f1

metric_validation:
  recall_at_k: [1, 10, 100]
  distance: cos  # options: cos, l2
  knn_k: 10
  keep_last_n_emb_steps: 10

neptune:
  project: -
  api_token: ***
  experiment_name: text-classification-run
  run_id: null
  tags: [metric-wise]
  dependencies_path: .
  # env_path: .env
